name: banknote
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_svg: ^2.0.7
  dio: ^5.3.2
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  device_preview: ^1.1.0
  hexcolor: ^3.0.1
  pretty_dio_logger: ^1.3.1
  quiver: ^3.2.1
  loading_indicator: ^3.1.1
  easy_localization: ^3.0.3
  flrx_validator: ^0.6.0
  firebase_messaging: ^14.6.7
  image_picker: ^0.8.7+5
  cached_network_image: ^3.2.3
  dotted_border: ^2.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logodark.png"
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets\images\Splash.png
    - assets\images\logo1.png
    - assets\images\logo.png
    - assets\images\coin1.png
    - assets\images\coin2.png
    - assets\images\page3.png
    - assets\images\startImage.png
    - assets\images\startLOGO.png
    - assets\images\startText.png
    - assets\images\logodark.png
    - assets\images\Screen.jpg
    - assets\icon\Calling.png
    - assets\icon\Lock.png
    - assets\icon\facebook.png
    - assets\icon\google.png
    - assets\icon\Message.png
    - assets\icon\Profile.png
    - assets\images\home.png
    - assets\icon\Database_light.png
    - assets\icon\Credit card_light.png
    - assets\icon\Chat.png
    - assets\icon\Notification.png
    - assets\icon\Setting.png
    - assets\icon\Ellipse 1653.png
    - assets\icon\black square.png
    - assets\icon\white square.png
    - assets\icon\recivmessage.png
    - assets\images\person.png
    - assets\images\rightLogo.png
    - assets\icon\Icon Home Active.png
    - assets\icon\Check List Icon.png
    - assets\icon\Upload.png
    - assets\JSON\policy.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
